Iter13
SversusN/shortener pull request #13
Opened 2024-06-05 18:40 UTC by SversusN

2024-06-09 22:37 UTC, avhitrov requested changes
Есть некоторые ошибки в реализации. Подробности в комментариях.

2024-06-09 22:37 UTC, avhitrov commented on internal/app/app.go
> +	ctx := context.TODO() //определится по требованиям
```suggestion
	ctx := context.Background() //определится по требованиям
```
В этом месте можно смело стартовать контекст приложения и использовать его потом для мягкой остановки сервиса.

2024-06-09 22:37 UTC, avhitrov commented on internal/handlers/handlers.go
> +			res.WriteHeader(http.StatusConflict)
При выставлении статуса ответа несколько раз за один запрос приводит к возникновению ошибки в логах:
```
2024/06/10 01:17:46 http: superfluous response.WriteHeader call from github.com/SversusN/shortener/internal/logger.(*loggingResponseWriter).WriteHeader (logger.go:44)
```
http-cервер в итоге выставляет только один заголовок, чтобы не путать клиентов, но это не значит, что можно спокойно скармливать их в цикле.

2024-06-09 22:37 UTC, avhitrov commented on internal/handlers/handlers.go
> +	}
Вторая проблема, связанная с данным кодом, заключается в неоднозначности ответа при возникновении ошибок в процессе сохранения. Например: первый url сохранился нормально, второй - с конфликтом, то пользователю будет выдан ответ 201 Created, хотя на самом деле батч будет сохранен лишь частично.

Третья проблема, связанная с разделением во времени чтения (`h.s.GetKey(r.OriginalURL)`) и записи (`err := h.s.SetURLBatch(saveUrls)`) подробно описана здесь: https://t.me/bushigo/35
В применении к данному коду DATA RACE будет выглядеть так: в два хендлера одновременно приходит запрос на сохранение одного и того же url (от разных пользователей). Оба хендлера примерно в одно и то же время получают ответ о том, что url отсутствует в БД. И оба пытаются записать, исходя из представления о том, что запись возможна. Один в итоге получит нормальную обработку, второй - conflict error. В случае с единичной записью это будет просто 500, выставленная клиенту. А вот в случае батча уже выставлен код `http.StatusCreated`, что совсем введет в заблуждение.

Правильным решением в данном случае будет вынос операции проверки существования url и записи в одну транзакцию стораджа (Внимание! есть подводные камни! https://t.me/bushigo/36).

2024-06-12 13:39 UTC, SversusN commented on internal/app/app.go
> +	ctx := context.TODO() //определится по требованиям
Планирую https://habr.com/ru/articles/771626/
Пока мне не все понятно.

2024-06-12 13:39 UTC, SversusN commented on internal/handlers/handlers.go
> +			res.WriteHeader(http.StatusConflict)
Поправлено. Было еще пара мест, где заголовок выставлялся без цикла. =)

2024-06-12 13:40 UTC, SversusN commented on internal/handlers/handlers.go
> +	}
Вынесено в одну функцию во всех стораджах. Убран обязательный метод для интерфейса. Учел скулёвое поведение

2024-06-17 20:34 UTC, avhitrov approved these changes
Все замечания исправлены. Аппрув!

2024-06-18 08:15 UTC, merged