Iter15
SversusN/shortener pull request #15
Opened 2024-06-22 11:30 UTC by SversusN

2024-06-26 21:52 UTC, avhitrov requested changes
Первое, что хотелось бы увидеть - поддержку всех функций всеми стораджами, что приводит
1. Избавлению от отдельной сущности - хранения списка пользовательский uid.
2. К генерации user_id на уровне приложения (например UUID), а не средствами СУБД
3. К небольшому рефакторингу файлового и in-memory хранилищ.

Кроме того, есть некоторое количество замечаний по работе с БД и организации транзакций. Все в комментариях к коду.

2024-06-26 21:52 UTC, avhitrov commented on internal/app/app.go
> +		ns, err = dbstorage.NewDB(cfg.DataBaseDSN, &ctx)
```suggestion
		ns, err = dbstorage.NewDB(ctx, cfg.DataBaseDSN)
```
Контекст принято передавать первым элементом, и передается он не по адресу, а напрямую. Если посмотреть в код, то функция Background() возвращает интерфейс. Интерфейс - ссылочный тип данных в Go.

2024-06-26 21:52 UTC, avhitrov commented on internal/app/app.go
> +	//ИД пользователя выдает постгрес, иначе мв не включаем
Вообще все стораджи должны поддерживать все вводимые функции. Соответственно, авторизация (а в данном проекте это скорее сессионирование) должна быть либо поддерживаться всеми стораджами, либо быть независимой от них.

2024-06-26 21:52 UTC, avhitrov commented on internal/middleware/authmw.go
> +				w.Write([]byte("pls, clear cookie data"))
Здесь надо либо `return`, чтобы не пытаться навешать еще ошибок, либо сгенерить новый код и идти дальше. Выставлять `StatusBadRequest` и дальше продолжать какие-то вычисления нет никакого смысла.

2024-06-26 21:52 UTC, avhitrov commented on internal/middleware/authmw.go
> +		userID, err := saver.CreateUser(r.Context())
Продолжу мысль. Для данного проекта совсем не обязательно сохранять в БД отдельную сущность "пользователь", так как пресловутый UserID - это по сути SessionID. Его можно генерить хоть через UUID и нужен он только для связи конкретного браузера с определенными действиями в системе. Поэтому не следует исключать поддержку операций с пользовательскими UUID для in-memory и файлового стораджей.

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	}
```suggestion
	if err != nil {
		return "", fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer func() {
		if err != nil {
			tx.Rollback()
		}
	}()
```
Если при `pg.db.Begin()` возникнет ошибка, то tx будет равен `nil`. В этом случае попытка вызвать от него `Rollback()` приведет к панике. А вот если в процессе обслуживания какого-либо из запросов возникнет ошибка, то нам необходимо будет сделать откат. Формально, можно дергать даже 
```
defer tx.Rollback()
```
так как, если перед ним будет выполнен Commit, то фугкция просто сработает вхолостую.

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	}
Те же самые замечания, что и для SetUserURL. После любой неудачи в процессе обработки запросов необходимо делать `return err`, а в defer засунуть Rollback.

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +		return 0, errors.New("postgres create userId")
```suggestion
		return 0, fmt.Errorf("postgres create userId: %w", err)
```
не забываем оборачивать ошибки. Хотя про уместность сохранения user id в отдельной таблицы в данном проекте я уже писал выше.

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	if err != nil || rows.Err() != nil {
```suggestion
	if err != nil {
```

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
    return nil, err
}
```

2024-06-26 21:52 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	go func() {
```
defer tx.Rollback()
```
иначе имеем приличный шанс дернуть Commit после Rollback, а это совсем не то же самое, что Rollback после Commit.

2024-06-26 21:52 UTC, avhitrov commented on internal/handlers/handlers.go
> +	go func() {
Это рабочий код, но при этом реализован очень "псевдо" fan-in. Гораздо эффективней просто дернуть горутину, которая вызовет функцию однократного апдейта по пачке идентификаторов (с помощью postgres-функции ANY).  Примерно так:
```
UPDATE URLS set is_deleted = true WHERE user_id = $1 AND short_url = ANY($2)
```
И вторым значением сразу передать слайс коротких урлов.

Хотя "честный" fan-in в данном проекте вообще не слишком применим. Как минимум, является не самым эффективным решением.

2024-06-30 19:10 UTC, SversusN commented on internal/app/app.go
> +		ns, err = dbstorage.NewDB(cfg.DataBaseDSN, &ctx)
+

2024-06-30 19:11 UTC, SversusN commented on internal/app/app.go
> +	//ИД пользователя выдает постгрес, иначе мв не включаем
+

2024-06-30 19:15 UTC, SversusN commented on internal/middleware/authmw.go
> +		userID, err := saver.CreateUser(r.Context())
+

2024-06-30 19:19 UTC, SversusN commented on internal/storage/dbstorage/dbstorage.go
> +	}
+

2024-06-30 19:19 UTC, SversusN commented on internal/storage/dbstorage/dbstorage.go
> +		return 0, errors.New("postgres create userId")
убрано

2024-06-30 19:27 UTC, SversusN commented on internal/handlers/handlers.go
> +	go func() {
+

2024-07-04 22:15 UTC, avhitrov approved these changes
Почти отлично. Практически все замечания исправлены, очень хорошо, что теперь все стораджи поддерживают весь набор операций. Осталась одна недопонятая концепция выбора данных из БД, а именно использование rows.Next() и rows.Err(). Сейчас ставлю апрув, чтобы не тормозить, но категорически жду исправления в следующих итерациях.

2024-07-04 22:15 UTC, avhitrov commented on internal/storage/dbstorage/dbstorage.go
> +	}
Перебрось за пределы цикла. Эту ошибку необходимо проверять только после того, как rows.Next() выдаст false (и цикл, соотвтетственно, завершится). Иначе мы так никогда и не узнаем, почему этот цикл завершился - записи кончились или ошибка возникла. Внутри цикла, если уж мы туда попали, rows.Err() всегда будет nil.

2024-07-05 07:27 UTC, SversusN commented on internal/storage/dbstorage/dbstorage.go
> +	}
Действительно пропустил...

2024-07-05 07:50 UTC, merged