Iter23
SversusN/shortener pull request #23
Opened 2024-09-14 02:40 UTC by SversusN

2024-09-17 22:56 UTC, avhitrov requested changes
В процессе реализации мягкого шатдауна забыты хендлеры `HandlerDeleteUserURLs`, которые "выстреливают" горутины, пытающиеся асинхронно удалить значения из стораджа. Чтобы не возникла неконсистентность, необходимо перед завершением приложения (но после остановки http-сервиса) дождаться завершения работы всех этих горутин. Например, пробросив в них WaitGroup.

2024-09-18 11:02 UTC, SversusN commented
+

2024-09-20 21:39 UTC, avhitrov approved these changes
Годная реализация, есть явно забытая WaitGroup, которая объявлена, но не используется. Это мусор, его надо убрать, но на работу, по стечению обстоятельств, он не влияет. Посему аппрув.

2024-09-20 21:39 UTC, avhitrov commented on internal/app/app.go
> +	wg.Add(3)
Не очень понятно, для чего объявлена WaitGroup. Без wg.Done() и wg.Wait() она не имеет никакого смысла.

2024-09-21 00:27 UTC, merged