Iter25
SversusN/shortener pull request #25
Opened 2024-10-06 16:03 UTC by SversusN

2024-10-06 16:36 UTC, SversusN commented
Прошу прощения, за такой небрежный код. Осознаю необходимость сервисного слоя. К сожалению, сейчас очень ограничен во времени в командировке, поэтому позволил массу повторяющейся логики.

2024-10-06 20:42 UTC, avhitrov requested changes
Практически все хорошо, кроме проверки на старт-стоп gRPC сервера.

2024-10-06 20:42 UTC, avhitrov commented on internal/app/app.go
> +			log.Printf("listen tcp has failed: %v", err)
Здесь явно не хватает проверок.
1. Если в конфиге GRPCAddress не указан, то сервер запускать не следует
2. Если сервер не запущен, необходимо каким-то образом сообщать в блок с graceful shutdown, что его не надо гасить
3. Если сервер не запустился из-за какой-то ошибки, следует либо падать по Fatal (если мы ожидаем, что сервер должен быть запущен), либо опять же передавать в graceful shutdown, что сервер не запущен. Считаю вариант с "падать по Fatal" более правильным, но оставляю на откуп.

2024-10-06 20:42 UTC, avhitrov commented on internal/app/app.go
> +	log.Printf("running grpc on %s\n", a.Config.GRPCAddress)
Утверждение верно только в случае, если GRPCAddress указан, указан верно, и сервер не упал при старте. Можно организовать на уровне main переменную atomic.Bool и устанавливать ее в соответствующее значение.

2024-10-08 17:22 UTC, SversusN commented on internal/app/app.go
> +			log.Printf("listen tcp has failed: %v", err)
Посчитал, что сервер GRPC не основная функциональность и добавил атомарное глобальное состояние.

2024-10-08 17:36 UTC, SversusN commented on internal/app/app.go
> +	log.Printf("running grpc on %s\n", a.Config.GRPCAddress)
Просто убрал лог. Он был нужен раньше для контроля и тестов.

2024-10-09 22:07 UTC, avhitrov approved these changes
Все ок! Поздравляю!

2024-10-10 15:34 UTC, merged